version: 2.1
orbs:
  win: circleci/windows@2.4.0  
  aws-cli: circleci/aws-cli@1.4.0

executors:
  go-1_15:
    working_directory: '/go/src/github.com/influxdata/telegraf'
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.15.8'
    environment:
      GOFLAGS: -p=8
  go-1_16:
    working_directory: '/go/src/github.com/influxdata/telegraf'
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.16.2'
    environment:
      GOFLAGS: -p=8
  mac:
    macos:
      xcode: 12.4.0
    working_directory: '~/go/src/github.com/influxdata/telegraf'
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      GOFLAGS: -p=8

commands:
  test-go:
    parameters:
      goarch:
        type: string
        default: "amd64"
    steps:
      - checkout
      - attach_workspace:
          at: '/go'
      - run: 'GOARCH=<< parameters.goarch >> make'
      - run: 'GOARCH=<< parameters.goarch >> make check'
      - run: 'GOARCH=<< parameters.goarch >> make check-deps'
      - run: 'GOARCH=<< parameters.goarch >> make test'
  package:
    parameters:
      nightly:
        type: boolean
        default: false
    steps:
      - checkout
      - attach_workspace:
          at: '/go'
      - when:
          condition: << parameters.nightly >>
          steps: 
            - run: 'NIGHTLY=1 make package'
            - run: 'make upload-nightly'
      - unless:
          condition: << parameters.nightly >>
          steps:
            - run: 'make package'
      - store_artifacts:
          path: './build/dist'
          destination: 'build/dist'
      - persist_to_workspace:
          root: './build'
          paths:
            - 'dist'
jobs:
  deps:
    executor: go-1_16
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run: 'make deps'
      - run: 'make tidy'
      - save_cache:
          name: 'go module cache'
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - persist_to_workspace:
          root: '/go'
          paths:
            - '*'
  test-go-1_15:
    executor: go-1_15
    steps:
      - test-go
  test-go-1_15-386:
    executor: go-1_15
    steps:
      - test-go:
          goarch: "386"
  test-go-1_16:
    executor: go-1_16
    steps:
      - test-go
  test-go-1_16-386:
    executor: go-1_16
    steps:
      - test-go:
          goarch: "386"
  test-go-mac:
    executor: mac
    steps:
      - checkout
      - restore_cache:
          key: mac-go-mod-v0-{{ checksum "go.sum" }}
      - run: 'sh ./scripts/mac_installgo.sh'
      - save_cache:
          name: 'Saving cache'
          key: mac-go-mod-v0-{{ checksum "go.sum" }}
          paths:
            - '/usr/local/Cellar/go'
            - '/usr/local/bin/go'
            - '/usr/local/bin/gofmt'
      - run: 'make deps'
      - run: 'make tidy'
      - run: 'make'
      - run: 'make check'
      - run: 'make test'


  package:
    executor: go-1_16
    steps:
      - package
  release:
    executor: go-1_16
    steps:
      - package
  nightly:
    executor: go-1_16
    steps:
      - package:
          nightly: true
                      
workflows:
  version: 2
  check:
    jobs:
      - 'deps':
          filters:
            tags:
              only: /.*/
      - 'test-go-1_15':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1_15-386':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1_16':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1_16-386':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-mac':
          filters:
            tags: # only runs on tags if you specify this filter
              only: /.*/
      - 'package':
          requires:
            - 'test-go-mac'
            - 'test-go-1_15'
            - 'test-go-1_15-386'
            - 'test-go-1_16'
            - 'test-go-1_16-386'
      - 'release':
          requires:
            - 'test-go-mac'
            - 'test-go-1_15'
            - 'test-go-1_15-386'
            - 'test-go-1_16'
            - 'test-go-1_16-386'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
  nightly:
    jobs:
      - 'deps'
      - 'test-go-1_15':
          requires:
            - 'deps'
      - 'test-go-1_15-386':
          requires:
            - 'deps'
      - 'test-go-1_16':
          requires:
            - 'deps'
      - 'test-go-1_16-386':
          requires:
            - 'deps'
      - 'test-go-mac'
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
